# Generated by Django 4.0.2 on 2022-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_profile_name_city_grid_img_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='username',
        ),
        migrations.AddField(
            model_name='guide',
            name='image',
            field=models.CharField(default='http', max_length=200),
        ),
    ]
