# Generated by Django 4.0.2 on 2022-02-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_guide_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='created_at',
        ),
    ]
