# Generated by Django 4.0.2 on 2022-02-15 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_guide_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
