# Generated by Django 4.0.2 on 2022-02-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_guide_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['-created_at']},
        ),
    ]
