# Generated by Django 4.0.2 on 2022-02-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_guide_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='image2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='image3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='image4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='image5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('bar', 'Bar'), ('arts', 'Arts'), ('nightlife', 'Nightlife'), ('culture', 'Culture'), ('sights', 'Sights'), ('cafes', 'Cafes'), ('shops', 'Shops'), ('outdoors', 'Outdoors')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
