# Generated by Django 4.0.2 on 2022-02-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_guide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
